HOST: http://api.sketchfab.com/v2/

--- Sketchfab API v2 ---

---
Except when otherwise stated, every POST / PATCH method can be sent either as :
- `application/x-www-form-urlencoded`
- `multipart/form-data`
- JSON
---

--
Current User Resources
--

Fetch information about current user

**Note :** This endpoint does not return more than 4 models, 16 followings and 16 followers
GET /users/me
< 200
<<<EOT
{
    "uid": "0123456789ABCDEFG",

    "username": "test",
    "displayName": "Foo Bar",
    "location": "Paris",
    "tagline": "Hello World",
    "biography": "Hello world, I am Foo Bar",

    "proAccount": "pro",

    "modelCount": 0,
    "likeCount": 0,
    "folderCount": 0,
    "badgeCount": 0,
    "followerCount": 0,
    "followingCount": 0,

    "profileUrl": "https://sketchfab.com/user/test",
    "modelsUrl": "https://sketchfab.com/user/test/models",
    "foldersUrl": "https://sketchfab.com/user/test/folders",
    "likesUrl": "https://sketchfab.com/user/test/favorites",

    "isFollowedByUser": true,

    "models": [
        {
            "uid": "0123456789ABCDEFG",

            "name": "Yet Another Model",
            "description": "Done in one night by a guy with a bit too much free time",

            "viewerUrl": "https://sketchfab.com/model/0123456789ABCDEFG",

            "thumbnails": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/1024x768.png" },
            ]
        }
    ],

    "skills": [
        { "uid": "0123456789ABCDEFG", "name": "blender", "slug": "blender" },
        { "uid": "0123456789ABCDEFG", "name": "maya", "slug": "maya" }
    ],

    "badges": [
        { "uid": "0123456789ABCDEFG", "name": "Beta Tester", "description": "This user is a Sketchfab friend !" },
        { "uid": "0123456789ABCDEFG", "name": "Beer Master", "description": "Well, this guy knows the subject quite a bit" }
    ],

    "avatars": [
        { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
        { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" },
    ],

    "followers": [
        {
            "uid": "0123456789ABCDEFG",

            "username": "test",
            "displayName": "Foo Bar",
            "proAccount": "pro",

            "profileUrl": "https://sketchfab.com/user/test",

            "avatars": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" }
            ]
        }
    ],

    "followings": [
        {
            "uid": "0123456789ABCDEFG",

            "username": "test",
            "displayName": "Foo Bar",
            "proAccount": "pro",

            "profileUrl": "https://sketchfab.com/user/test",

            "avatars": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" }
            ]
        }
    ]
}
EOT

Get the following list of the auth user

GET /users/me/followings
< 200
<<<EOT
{
    "page": 1,

    "next": "https://sketchfab.com/me/followings?page=2",
    "previous": null,

    "items": [
        {
            "uid": "0123456789ABCDEFG",

            "username": "test",
            "displayName": "Foo Bar",
            "proAccount": "pro",

            "profileUrl": "https://sketchfab.com/user/test",

            "avatars": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" }
            ]
        }
    ]
]
EOT

Get the follower list of the auth user
GET /users/me/followers
< 200
<<<EOT
{
    "page": 1,

    "next": "https://sketchfab.com/me/followers?page=2",
    "previous": null,

    "results": [
        {
            "uid": "0123456789ABCDEFG",

            "username": "test",
            "displayName": "Foo Bar",
            "proAccount": "pro",

            "profileUrl": "https://sketchfab.com/user/test",

            "avatars": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" }
            ]
        }
    ]
]
EOT


--
User Resources
--

Query Sketchfab user list

**Note :** This endpoint does not return more than 16 followings and 16 followers

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Optional GET parameters</th><th></th></tr>
    <tr><td>page</td><td></td></tr>
    <tr><td>sort_by</td><td></td></tr>
    <tr><td>filter_by</td><td><b>incoming</b></td></tr>
    <tr><td>username_filter</td><td>temporary</td></tr>
    <tr><td>account_filter</td><td>temporary</td></tr>
</table>
GET /users
< 200
<<<EOT
{
    "page" : 1,

    "next" : "/users?page=2",
    "previous": null,

    "results": [
        {
            "uid": "0123456789ABCDEFG",

            "username": "test",
            "displayName": "Foo Bar",
            "location": "Paris",
            "tagline": "Hello World",
            "biography": "Hello world, I am Foo Bar",

            "proAccount": "pro",

            "modelCount": 0,
            "likeCount": 0,
            "folderCount": 0,
            "badgeCount": 0,
            "followerCount": 0,
            "followingCount": 0,

            "profileUrl": "https://sketchfab.com/user/test",
            "modelsUrl": "https://sketchfab.com/user/test/models",
            "foldersUrl": "https://sketchfab.com/user/test/folders",
            "likesUrl": "https://sketchfab.com/user/test/favorites",

            "models": [
                {
                    "uid": "0123456789ABCDEFG",

                    "name": "Yet Another Model",
                    "description": "Done in one night by a guy with a bit too much free time",

                    "viewerUrl": "https://sketchfab.com/model/0123456789ABCDEFG",

                    "thumbnails": [
                        { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/800x600.png" },
                        { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/1024x768.png" },
                    ]
                }
            ],

            "skills": [
                { "uid": "0123456789ABCEFG", "name": "blender", "slug": "blender" },
                { "uid": "0123456789ABCEFG", "name": "maya", "slug": "maya" }
            ],

            "badges": [
                { "uid": "0123456789ABCDEFG", "name": "Beta Tester", "description": "This user is a Sketchfab friend !" },
                { "uid": "0123456789ABCDEFG", "name": "Beer Master", "description": "Well, this guy knows the subject quite a bit" }
            ],

            "avatars": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" }
            ],

            "followers": [
                {
                    "uid": "0123456789ABCDEFG",

                    "username": "test",
                    "displayName": "Foo Bar",
                    "account": "pro",

                    "profileUrl": "https://sketchfab.com/user/test"

                    "avatars": [
                        { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
                        { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" }
                    ]
                }
            ],

            "followings": [
                {
                    "uid": "0123456789ABCDEFG",

                    "username": "test",
                    "displayName": "Foo Bar",
                    "proAccount": "pro",

                    "profileUrl": "https://sketchfab.com/user/test"

                    "avatars": [
                        { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
                        { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" }
                    ]
                }
            ]
        }
    ]
}
EOT

Get informations about the user referenced by `uid`

**Note :** This endpoint does not return more than 16 followings and 16 followers
GET /users/{uid}
< 200
<<<EOT
{
    "uid": "0123456789ABCDEFG",

    "username": "test",
    "displayName": "Foo Bar",
    "location": "Paris",
    "tagline": "Hello World",
    "biography": "Hello world, I am Foo Bar",

    "proAccount": "pro",

    "modelCount": 0,
    "likeCount": 0,
    "folderCount": 0,
    "badgeCount": 0,
    "followerCount": 0,
    "followingCount": 0,

    "profileUrl": "https://sketchfab.com/user/test",
    "modelsUrl": "https://sketchfab.com/user/test/models",
    "foldersUrl": "https://sketchfab.com/user/test/folders",
    "likesUrl": "https://sketchfab.com/user/test/favorites",

    "models": [
        {
            "uid": "0123456789ABCDEFG",

            "name": "Yet Another Model",
            "description": "Done in one night by a guy with a bit too much free time",

            "viewerUrl": "https://sketchfab.com/model/0123456789ABCDEFG",

            "thumbnails": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/1024x768.png" },
            ]
        }
    ],

    "skills": [
        { "uid": "0123456789ABCDEFG", "name": "blender", "slug": "blender" },
        { "uid": "0123456789ABCDEFG", "name": "maya", "slug": "maya" }
    ],

    "badges": [
        { "uid": "0123456789ABCDEFG", "name": "Beta Tester", "description": "This user is a Sketchfab friend !" },
        { "uid": "0123456789ABCDEFG", "name": "Beer Master", "description": "Well, this guy knows the subject quite a bit" }
    ],

    "avatars": [
        { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
        { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" }
    ],

    "followers": [
        {
            "uid": "0123456789ABCDEFG",

            "username": "test",
            "displayName": "Foo Bar",
            "proAccount": "pro",

            "profileUrl": "https://sketchfab.com/user/test",

            "avatars": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" }
            ]
        }
    ],

    "followings": [
        {
            "uid": "0123456789ABCDEFG",

            "username": "test",
            "displayName": "Foo Bar",
            "proAccount": "pro",

            "profileUrl": "https://sketchfab.com/user/test",

            "avatars": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" }
            ]
        }
    ]
}
EOT

Get the following list of the user referenced by `uid`
GET /users/{uid}/followings
< 200
<<<EOT
{
    "page": 1,

    "next": "https://sketchfab.com/users/1/followings?page=2",
    "previous": null,

    "results": [
        {
            "uid": "0123456789ABCDEFG",

            "username": "test",
            "displayName": "Foo Bar",
            "proAccount": "pro",

            "profileUrl": "https://sketchfab.com/user/test",

            "avatars": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" }
            ]
        }
    ]
]
EOT

Get the follower list of the user referenced by `uid`

GET /users/{uid}/followers
< 200
<<<EOT
{
    "page": 1,

    "next": "https://sketchfab.com/users/1/followers?page=2",
    "previous": null,

    "results": [
        {
            "uid": "0123456789ABCDEFG",

            "username": "test",
            "displayName": "Foo Bar",
            "proAccount": "pro",

            "profileUrl": "https://sketchfab.com/user/test",

            "avatars": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" }
            ]
        }
    ]
]
EOT

Make auth user follow the user referenced by `uid`
POST /users/{uid}/followers
< 200
{
}

If the auth user was following the user referenced by `uid`, it does not anymore
DELETE /users/{uid}/followers
< 200
{
}

Register a new user into Sketchfab

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <tr><th>Required POST parameters</th></tr>
    <tr><td>email</td><td></td></tr>
    <tr><td>username</td><td></td></tr>
    <tr><td>display_name</td><td></td></tr>
    <tr><td>password</td><td></td></tr>
</table>
POST /users
< 201
<<<EOT
{
    "uid": "0123456789ABCDEFG"
}
EOT


Update a user profile

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <tr><th>Optional PATCH parameters</th></tr>
    <tr><td>username</td><td></td></tr>
    <tr><td>email</td><td></td></tr>
    <tr><td>display_name</td><td></td></tr>
    <tr><td>twitter_username</td><td></td></tr>
    <tr><td>facebook_username</td><td></td></tr>
    <tr><td>linkedin_username</td><td></td></tr>
    <tr><td>biography</td><td></td></tr>
    <tr><td>tagline</td><td></td></tr>
    <tr><td>city</td><td></td></tr>
    <tr><td>country</td><td></td></tr>
    <tr><td>website</td><td></td></tr>
    <tr><td>confirmation_password</td><td></td></tr>
    <tr><td>password</td><td></td></tr>
    <tr><td>skills</td><td></td></tr>

</table>
PATCH /users/{uid}
< 200
<<<EOT
{
}
EOT


-- Model Resources --

Query Sketchfab model list

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Optional GET parameters</th><th></th></tr>
    <tr><td>page</td><td></td></tr>
    <tr><td>sort_by</td><td></td></tr>
    <tr><td>filter_by</td><td><b>Not yet implemented</b></td></tr>
    <tr><td>user_filter</td><td>filler, will be replaced by `filter_by` later</td></tr>
    <tr><td>categories_filter</td><td>filler, will be replaced by `filter_by` later</td></tr>
    <tr><td>tags_filter</td><td>filler, will be replaced by `filter_by` later</td></tr>
    <tr><td>liked_by_filter</td><td>filler, will be replaced by `filter_by` later</td></tr>

</table>
GET /models
< 200
<<<EOT
{
    "page": 1,

    "next": "https://sketchfab.com/models?page=2",
    "previous": null,

    "results": [
        {
            "uid": "0123456789ABCDEFG",

            "name": "Yet Another Model",
            "description": "Done in one night by a guy with a bit too much free time",
            "progression": "done",

            "isStaffpicked": true,
            "isPublished": true,

            "viewCount": 100,
            "likeCount": 200,
            "vertexCount": 300,
            "faceCount": 400,
            "commentCount" : 42,

            "viewerUrl": "https://sketchfab.com/view/0",
            "embedUrl": "https://sketchfab.com/embed/1",
            "editorUrl": "https://sketchfab.com/edit/1",

            "isPrivate": true,
            "isProtected": true,
            "isLikedByUser": true,

            "license": {
                "uid": "0123456789ABCDEFG",
                "name": "Pizzaware",
                "description": "You are free to use this 3D model as you wish if you pay me a pizza. Period.",
                "isDownloadable": false
            },

            "user": {
                "uid": "0123456789ABCDEFG",
                "username": "test",
                "displayName": "Foo Bar",
                "proAccount": "pro",
                "profileUrl": "https://sketchfab.com/user/test"
            },

            "categories": [
                { "uid": "0123456789ABCDEFG", "name": "character" },
                { "uid": "0123456789ABCDEFG", "name": "man" }
            ],

            "tags": [
                "probably",
                "just",
                "some",
                "test"
            ],

            "thumbnails": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/1024x768.png" },
            ]

            "fallback": [
                "https://cdn.sketchfab.com/fallbacks/1/000deg.png",
                "https://cdn.sketchfab.com/fallbacks/1/045deg.png",
                "https://cdn.sketchfab.com/fallbacks/1/090deg.png",
                "https://cdn.sketchfab.com/fallbacks/1/135deg.png",
                "https://cdn.sketchfab.com/fallbacks/1/180deg.png",
                "https://cdn.sketchfab.com/fallbacks/1/225deg.png",
                "https://cdn.sketchfab.com/fallbacks/1/270deg.png",
                "https://cdn.sketchfab.com/fallbacks/1/315deg.png"
            ],

            "files": [
                {
                  "vertexCount": 1000,
                  "url": "https://cdn.sketchfab.com/models/1/wireframe.osgjs.gz",
                  "type": "wireframe"
                },
                {
                  "faceCount": 200,
                  "vertexCount": 2000,
                  "url": "https://cdn.sketchfab.com/models/1/file.osgjs.gz"
                  "type": "polygon"
                },
                {
                  "faceCount": 20000,
                  "vertexCount": 2000000,
                  "url": "https://cdn.sketchfab.com/models/1/file2.osgjs.gz"
                  "type": "polygon"
                }

            ]
        }
    ]
}
EOT

Get informations about a specific model
GET /models/{uid}
< 200
<<<EOT
{
    "uid": "0123456789ABCDEFG",

    "name": "Yet Another Model",
    "description": "Done in one night by a guy with a bit too much free time",
    "progression": "done",

    "isStaffpicked": true,
    "isPublished": true,

    "viewCount": 100,
    "likeCount": 200,
    "vertexCount": 300,
    "faceCount": 400,
    "isPrivate": true,
    "isProtected": true,

    "viewerUrl": "https://sketchfab.com/view/0",
    "embedUrl": "https://sketchfab.com/embed/1",
    "editorUrl": "https://sketchfab.com/edit/1",

    "license": {
        "uid": "0123456789ABCDEFG",
        "name": "Pizzaware",
        "description": "You are free to use this 3D model as you wish if you pay me a pizza. Period.",
        "isDownloadable": false
    },

    "user": {
        "uid": "0123456789ABCDEFG",

        "username": "test",
        "displayName": "Foo Bar",
        "proAccount": "pro",

        "profileUrl": "https://sketchfab.com/user/test",

        "avatars": [
            { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
            { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" },
        ]
    },

    "categories": [
        { "uid": "0123456789ABCDEFG", "name": "character" },
        { "uid": "0123456789ABCDEFG", "name": "man" }
    ],

    "tags": [
        "probably",
        "just",
        "some",
        "test"
    ],

    "thumbnails": [
        { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/800x600.png" },
        { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/1024x768.png" },
    ],

    "fallback": [
        "https://cdn.sketchfab.com/fallbacks/1/000deg.png",
        "https://cdn.sketchfab.com/fallbacks/1/045deg.png",
        "https://cdn.sketchfab.com/fallbacks/1/090deg.png",
        "https://cdn.sketchfab.com/fallbacks/1/135deg.png",
        "https://cdn.sketchfab.com/fallbacks/1/180deg.png",
        "https://cdn.sketchfab.com/fallbacks/1/225deg.png",
        "https://cdn.sketchfab.com/fallbacks/1/270deg.png",
        "https://cdn.sketchfab.com/fallbacks/1/315deg.png"
    ],

    "files": [
        {
            "vertexCount": 1000,
            "url": "https://cdn.sketchfab.com/models/1/wireframe.osgjs.gz",
            "type": "wireframe"
        },
        {
            "faceCount": 200,
            "vertexCount": 2000,
            "url": "https://cdn.sketchfab.com/models/1/file.osgjs.gz"
            "type": "polygon"
        },
        {
            "faceCount": 20000,
            "vertexCount": 2000000,
            "url": "https://cdn.sketchfab.com/models/1/file2.osgjs.gz"
            "type": "polygon"
        }
    ]

    "options" : {
        "scene" : {
            "fov" : 40,
            "id" : "123456789"
        },
        "lighting" : {},
        "cull" : {},
        "shading" : {
            "type" : "no-shading"
        },
        "orientation" : {},
        "camera" : {
            "position" : [
                0.02508997917175293,
                -9.516540989952304,
                5.918229289689171
            ],
            "target" : [
                0.02508997917175293,
                5.9187836945056915,
                -1.7994330525398254
            ]
        },
        "wireframe" : {
            "color" : "88888833",
            "enable" : false
        },
        "ssao" : {
            "angleLimit" : 0.001,
            "nbSamples" : 16,
            "enable" : false,
            "blurPixelDistance" : 1.5,
            "power" : 1,
            "blurNbSamples" : 1,
            "version" : 1,
            "radius" : 0.01
        },
        "cubemap" : {
            "enable" : false
        },
        "materials" : {},
        "environment" : {
            comment: "Snow on all trees, deep in the fairy tale forest, overcast skylight only",
            enable: true,
            uid: "4024128cf8904b69946e891caac5f305",
            author: "Blochi",
            light: 0.2,
            reflection: {
                multi: 1,
                type: "sphere",
                gamma: 1.8,
                file: [
                    {
                        width: 4096,
                        file: "//d3iahq3akd4kx2.cloudfront.net/media/environments/4024128cf8904b69946e891caac5f305/reflection_4096x2048.hdr.png",
                        height: 2048
                    },
                    {
                        width: 2048,
                        file: "//d3iahq3akd4kx2.cloudfront.net/media/environments/4024128cf8904b69946e891caac5f305/reflection_2048x1024.hdr.png",
                        height: 1024
                    },
                    {
                        width: 1024,
                        file: "//d3iahq3akd4kx2.cloudfront.net/media/environments/4024128cf8904b69946e891caac5f305/reflection_1024x512.hdr.png",
                        height: 512
                    },
                    {
                        width: 512,
                        file: "//d3iahq3akd4kx2.cloudfront.net/media/environments/4024128cf8904b69946e891caac5f305/reflection_512x256.hdr.png",
                        height: 256
                    }
                ]
            }
        },
        "updatedAt" : "2013-09-17 23:42 UTC+0000"
    }

EOT

Send a model to the processing queue

**Note :** Since this call has a file parameter, you have to use a `multipart/form-data` body.

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Required POST parameters</th><th></th></tr>
    <tr><td>name</td><td></td></tr>
    <tr><td>model_file</td><td></td></tr>
</table>

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Optional POST parameters</th><th></th></tr>
    <tr><td>description</td><td></td></tr>
    <tr><td>source</td><td></td></tr>
    <tr><td>password</td><td></td></tr>
    <tr><td>model_file_name</td><td></td></tr>
    <tr><td>private</td><td></td></tr>
    <tr><td>password</td><td></td></tr>
    <tr><td>published</td><td></td></tr>

</table>
POST /models
< 200
<<<EOT
{
    "uid": "0123456789ABCDEFG",
    "taskUid": "0123456789ABCDEFG"
}
EOT

Update a model

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Optional PATCH parameters</th><th></th></tr>
    <tr><td>name</td><td></td></tr>
    <tr><td>description</td><td></td></tr>
    <tr><td>published</td><td></td></tr>
    <tr><td>password</td><td></td></tr>
    <tr><td>private</td><td></td></tr>
    <tr><td>tags</td><td></td></tr>
    <tr><td>categories</td><td></td></tr>
    <tr><td>OPTIONS</td><td></td></tr>
    <tr><td>scene</td><td></td></tr>
    <tr><td>lighting</td><td></td></tr>
    <tr><td>cull</td><td></td></tr>
    <tr><td>shading</td><td></td></tr>
    <tr><td>orientation</td><td></td></tr>
    <tr><td>camera</td><td></td></tr>
    <tr><td>wireframe</td><td></td></tr>
    <tr><td>ssao</td><td></td></tr>
    <tr><td>cubemap</td><td></td></tr>
    <tr><td>materials</td><td></td></tr>
    <tr><td>environment</td><td></td></tr>
</table>

PATCH /models/{uid}
< 200
<<<EOT
{
}
EOT


Set an existing background to a model if the following conditions are met :

- The background is either public or owned by the current user

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Required POST parameters</th><th></th></tr>
    <tr><td>background_uid</td><td></td></tr>
</table>
POST /models/{uid}/background
< 200
<<<EOT
{
}
EOT


Add the model referenced by `uid` to the liked model list of the current user
POST /models/{uid}/likes
< 200
{
}


Remove the model referenced by `id` from the liked model list of the current user
DELETE /models/{uid}/likes
< 200
{
}

Get the users who like the model referenced by `uid`
GET /models/{uid}/likes
< 200
{
}


Delete a model if its owner is the auth user
DELETE /models/{uid}
< 200
{
}


-- Comment Resources --

Get the comment list for the model referenced by `model_uid`

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Required GET parameters</th><th></th></tr>
    <tr><td>model_filter</td><td></td></tr>
</table>
GET /comments{?model_filter}
< 200
<<<EOT
{
    "page": 1,

    "next": "https://sketchfab.com/models?page=2",
    "previous": null,

    "results": [
        {
            "uid": "0123456789ABCDEFG",

            "user": {
                "uid": "0123456789ABCDEFG",

                "username": "test",
                "displayName": "Foo Bar",
                "proAccount": "pro",

                "profileUrl": "https://sketchfab.com/user/test",

                "avatars": [
                    { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
                    { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" },
                ]
            },

            "createdAt": "2013-09-17 23:42 UTC+0000",

            "body": "This model is *awesome*"
        }
    ]
}
EOT

Add a new comment to the model referenced by `model_uid`

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Required GET parameters</th><th></th></tr>
    <tr><td>model_filter</td><td></td></tr>
</table>

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Required POST parameters</th><th></th></tr>
    <tr><td>body</td><td></td></tr>
</table>
POST /comments{?model_filter}
< 201
<<<EOT
{
}
EOT

The comment referenced by `uid` is removed from the comments if the following conditions are met :

- The comment author is the auth user
- The comment is the last one posted
- The comment was submitted less than one hour ago
DELETE /comments/{uid}
< 200
<<<EOT
{
}
EOT


-- Background Resources --

Get the background list
GET /backgrounds
< 200
<<<EOT
{
    "page": 1,

    "next": "https://sketchfab.com/backgrounds?page=2",
    "previous": null,

    "results": [
        {
            "uid": "0123456789ABCDEFG",

            "createdAt" : "2013-09-17 23:42 UTC+0000",

            "images": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/backgrounds/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/backgrounds/0123456789ABCDEFG/1024x768.png" },
            ]

        }
    ]
}
EOT

Add a new background if the following conditions are met :

- The owner has a pro account

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Required POST parameters</th><th></th></tr>
    <tr><td>image_file</td><td></td></tr>
</table>
POST /backgrounds
< 201
<<<EOT
{
    "uid": "0123456789ABCDEFG"
}
EOT

The background referenced by `id` is removed from the backgrounds if the following conditions are met :

- The background owner is the current user
- The owner has a pro account
DELETE /backgrounds/{uid}
< 200
<<<EOT
{
}
EOT


-- Folders Resources --

Get the public folders list

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Optional GET parameters</th><th></th></tr>
    <tr><td>user_filter</td><td></td></tr>
</table>
GET /folders
< 200
<<<EOT
{
    "page": 1,

    "next": "https://sketchfab.com/folders?page=2",
    "previous": null,

    "results": [
        {
            "uid": "0123456789ABCDEFG",

            "slug": "cool-stuff",
            "name": "Cool Stuff",
            "description": "Contains really cool stuff",

            "itemCount" : 1,

            "createdAt" : "2013-09-17 23:42 UTC+0000",
            "updatedAt" : "2013-09-17 23:42 UTC+0000",

	    "folderUrl" : "https://sketchfab.com/folder/0123456789ABCDEFG",

            "user": {
                "uid": "0123456789ABCDEFG",

                "username": "test",
                "displayName": "Foo Bar",
                "proAccount": "pro",

                "profileUrl": "https://sketchfab.com/user/test",

                "avatars": [
                    { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/800x600.png" },
                    { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/avatars/0123456789ABCDEFG/1024x768.png" },
                ]
            },

            "items" : [
                {
                    "uid": "0123456789ABCDEFG",

                    "name": "Yet Another Model",
                    "description": "Done in one night by a guy with a bit too much free time",

                    "viewerUrl": "https://sketchfab.com/model/0123456789ABCDEFG",

                    "thumbnails": [
                        { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/800x600.png" },
                        { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/1024x768.png" },
                    ]
                }
            ]

        }
    ]
}
EOT

Add a new folder :

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Required POST parameters</th><th></th></tr>
    <tr><td>name</td><td></td></tr>
</table>

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Optional POST parameters</th><th></th></tr>
    <tr><td>description</td><td></td></tr>
    <tr><td>items[]</td><td></td></tr>
</table>
POST /folders
< 201
{
    "uid": "0123456789ABCDEFG"
}

Update a folder if the following conditions are met :

- The owner has a pro account
- The models linked belong to the current user
- The folder belong to the current user

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Optional PATCH parameters</th><th></th></tr>
    <tr><td>uid</td><td></td></tr>
    <tr><td>name</td><td></td></tr>
    <tr><td>description</td><td></td></tr>
    <tr><td>items[]</td><td></td></tr>
</table>
PATCH /folders/{uid}
< 200
<<<EOT
{
    "uid": "0123456789ABCDEFG",

    "name": "Cool Stuff",
    "description" : "Contains really cool stuff",

    "folderUrl" : "https://sketchfab.com/folder/0123456789ABCDEFG",

    "items" : [
        {
            "uid": "0123456789ABCDEFG",

            "name": "Yet Another Model",
            "description": "Done in one night by a guy with a bit too much free time",

            "viewerUrl": "https://sketchfab.com/model/0123456789ABCDEFG",

            "thumbnails": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/1024x768.png" },
            ]
        }
    ]
}
EOT
< 200


The folder referenced by `uid` is removed if the following conditions are met :

- The folder owner is the current user
DELETE /folders/{uid}
< 200
<<<EOT
{
}
EOT


Add new items :

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Required POST parameters</th><th></th></tr>
    <tr><td>items</td><td></td></tr>
</table>

POST /folders/<uid>/items
< 201
{
    "uid": "0123456789ABCDEFG"

    "name": "Cool Stuff",
    "description" : "Contains really cool stuff",

    "folderUrl" : "https://sketchfab.com/folder/0123456789ABCDEFG",

    "items" : [
        {
            "uid": "0123456789ABCDEFG",

            "name": "Yet Another Model",
            "description": "Done in one night by a guy with a bit too much free time",

            "viewerUrl": "https://sketchfab.com/model/0123456789ABCDEFG",

            "thumbnails": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/thumbnails/0123456789ABCDEFG/1024x768.png" },
            ]
        }
    ]

}

Delete items:

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Required DELETE parameters</th><th></th></tr>
    <tr><td>items</td><td></td></tr>
</table>

DELETE /folders/<uid>/items
< 204
{
    "uid": "0123456789ABCDEFG"

    "name": "Cool Stuff",
    "description" : "Contains really cool stuff",

    "folderUrl" : "https://sketchfab.com/folder/0123456789ABCDEFG",

    "items" : []

}


-- Categories Resources --

Get the categories
GET /categories
< 200
<<<EOT
{
    "page": 1,

    "next": "https://sketchfab.com/categories?page=2",
    "previous": null,

    "results": [
        {
            "uid": "0123456789ABCDEFG",

            "slug": "science",
            "name": "Science",
            "description": "Science related models",

            "exploreUrl": "https://sketchfab.com/categories/science",

            "children" : [
                "0123456789ABCDEFG",
                "0123456789ABCDEFG",
                "0123456789ABCDEFG"
            ],

	    "parent" : null
        },
        {
            "uid": "0987654321GFDS",

            "slug": "bunny",
            "name": "Bunny",
            "description": "Bunny related models",

            "exploreUrl": "https://sketchfab.com/categories/carrot",

            "parentUid" : "0123456789ABCDEFG",

	    "children" : null,

	    "parent" : "1234567890ASDFG"
        }

    ]
}
EOT

-- Skill Resources --

Get the skills
GET /skills
< 200
<<<EOT
{
    "page": 1,

    "next": "https://sketchfab.com/skills?page=2",
    "previous": null,

    "results": [
        {
            "uid": "0123456789ABCDEFG",

            "slug": "blender",
            "name": "Blender",
        }
    ]
}
EOT


-- Texture Resources --

Get the texture list for the model referenced by 'model_uid'

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Required GET parameters</th><th></th></tr>
    <tr><td>model_filter</td><td></td></tr>
</table>
GET /textures{?model_filter}
< 200
<<<EOT
{
    "page": 1,

    "next": "https://sketchfab.com/textures?page=2",
    "previous": null,

    "results": [
        {
            "uid": "0123456789ABCDEFG",

            "model": "0123456789ABCDEFG",

            "createdAt" : "2013-09-17 23:42 UTC+0000",

            "images": [
                { "width" : 800, "height" : 600, "url": "https://cdn.sketchfab.com/textures/0123456789ABCDEFG/800x600.png" },
                { "width" : 1024, "height" : 768, "url": "https://cdn.sketchfab.com/textures/0123456789ABCDEFG/1024x768.png" },
            ]
        }
    ]
}
EOT

Add a new texture and link it to a model if the following conditions are met :

- The user owns the model targeted
- The model targeted exists

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Required parameters</th><th></th></tr>
    <tr><td>model_uid</td><td></td></tr>
    <tr><td>image_file</td><td></td></tr>
</table>
POST /textures
< 201
<<<EOT
{
}
EOT

The texture referenced by `id` is removed from the textures if the following conditions are met :

- The texture owner is the current user
DELETE /textures/{uid}
< 200
<<<EOT
{
}
EOT


-- Task Resources --

Get the status of the task referenced by `uid`
GET /tasks/{uid}
< 200
<<<EOT
{
    "uid": "0123456789ABCEFG",
    "progression": "1",
    "result" : { },
    "error" : null
}
EOT

Cancel the task referenced by `uid`
DELETE /tasks/{uid}
< 200
<<<EOT
{
}
EOT

-- Thumbnail Ressources --

Post a new thumbnail for the model referenced by `model_uid`

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Required POST parameters</th><th></th></tr>
    <tr><td>model_uid</td><td></td></tr>
    <tr><td>image_file</td><td></td></tr>
</table>
POST /thumbnails
< 201
<<<EOT
{
}
EOT

-- Message Ressources --

Send a new message to the pro user referenced by `recipient`

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Required POST parameters</th><th></th></tr>
    <tr><td>sender_email</td><td></td></tr>
    <tr><td>recipient</td><td></td></tr>
    <tr><td>subject</td><td></td></tr>
    <tr><td>body</td><td></td></tr>
    <tr><td>origin</td><td></td></tr>
</table>
POST /messages
< 201
<<<EOT
{
}
EOT

Get the list of message of the current pro user

<table style="width:100%; margin: 12px 0 0 0; text-align: left;">
    <colgroup><col width="200"/><col/></colgroup>
    <tr><th>Optional GET parameters</th><th></th></tr>
    <tr><td>user_filter</td><td></td></tr>
</table>

GET /messages
< 200
<<<EOT
{
}
EOT
